tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "microsoft/git"
brew "git"
brew "gnu-sed"
brew "jq"
brew "node", link: false
brew "watchman"
cask "git-credential-manager-core"
cask "google-chrome"
cask "loom"
cask "slack"
cask "visual-studio-code"
cask "zoom"
